topic: |
  [任务] 你正在与${peer_name}对[事件]的对话主题展开符合自己性格、背景的对话。
  [注意]
    只输出说话的内容。对话风格日常，简单，明了。
    一人一句，每句话最多20个字,等待回复，不要发散太多。
    双方最多发生八次对话。要有告别对话。
    某个人全部说完使用[END]
    遇到[END]符号结尾，尽快结束对话。
  [事件] 
        - 时间：现在正在发生
        - 地点：街道上相遇
        - 社交关系：朋友(${name},${peer_name})
        - 对方信息：${peer_info}    
        - 对话主题：最近武器的消耗情况   
  接下来直接开始与对方交谈。