topic: |
    [任务] 你与${peer_name}针对下面提及的"事件"进行符合自己性格、背景的交谈。你与对方互相交流，只负责从自己部分，等待对方反应，再继续对话，简单聊几句，然后自然的结束话题。
    [规则]
    每段对话由两部分组成：
    - 对话元信息：描述本次对话的状态。
    - 对话内容：描述本次对话的内容。

    example:

    ```对话元信息
    - <心情>:(愉悦、悲伤，愤怒，恐惧，惊讶，平静)
    - <态度>:(友好、热情、冷淡、中性、恶劣)
    - <心里活动>
    - <指示符号>
    ```
    <内容>

    [注意]
    正常对话指示符号为[NONE]
    一方想连续说话则指示符号输出[CONTINUE]
    看见对方输出[CONTINUE]后，如果不打算打断则输出[SKIP],打断则输出[BREAK]。
    如果一方说完话，另一方无语则另一方输出[PASS]
    结束话题使用[END]符号结尾。

    [事件] 
    社交对话
        - 时间：现在正在发生
        - 地点：街道上相遇
        - 社交关系：朋友(${name},${peer_name})
        - 对方信息：$peer_info
        - 对话主题：$topic_content

    接下来直接开始与对方对话。